### PR TITLE
Add support to implement audit log for failed scenarios (transit-move…

### PR DESCRIPTION
**Pull request by sonisn1988**
…ments-auditing)

### CODE REVIEW

**Comment by drnaylor** [comment]
Two things come to mind here:

* Are there any unit tests that check these objects?
* A lot of these events should have metadata associated with them. For example, `SubmitAttachMessageFailedEvent` -- should we have the message and message type associated with this event? How does that work -- what do we do?

The reason I'm nervous about this is because while we just convert messages to Json for message based audit events, we don't have a defined schema for other audit events. This means that we can just send what we want (we basically just send on whatever we receive from the calling service).

I think that we need to take a step back and consider what information each audit event needs and make sure they are defined here -- if we haven't done it yet (and right now, I don't think we have that).

**Comment by sonisn1988** [comment]
This is not required as of now as ticket needs to move back to 3 amigo

**Comment by sonisn1988** [comment]
> Two things come to mind here:
> 
> * Are there any unit tests that check these objects?
> * A lot of these events should have metadata associated with them. For example, `SubmitAttachMessageFailedEvent` -- should we have the message and message type associated with this event? How does that work -- what do we do?
> 
> The reason I'm nervous about this is because while we just convert messages to Json for message based audit events, we don't have a defined schema for other audit events. This means that we can just send what we want (we basically just send on whatever we receive from the calling service).
> 
> I think that we need to take a step back and consider what information each audit event needs and make sure they are defined here -- if we haven't done it yet (and right now, I don't think we have that).



> 

@drnaylor-oc  Yes we already have common test class ```AuditTypeSpec``` for AuditType that is written for all the events type using foreach.
regarding  second point we need to send Audit Failed payload from api and need to send as it is to auditing service.

**Comment by drnaylor** [comment]
Alright. Let's get this in as a good starting point, if we need to tweak it later, so be it.

**Review by drnaylor — APPROVED** [review]

**Pull request merged**
